<form class="form-horizontal" id="form-veiculo" action="<?php echo $this->action; ?>" data-edit="<?php echo !empty($this->veiculo) ?>" method="POST">
    <div class="form-group">
        <label class="control-label col-sm-3" for="placa">Placa:</label>
        <div class="col-sm-6">
            <input
                type="text"
                class="form-control"
                id="placa"
                name="placa"
                value="<?php echo $this->veiculo ? $this->veiculo->getPlaca() : null ?>"
            >
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-3" for="renavam">Renavam:</label>
        <div class="col-sm-6">
            <input
                type="text"
                class="form-control"
                id="renavam"
                name="renavam"
                value="<?php echo $this->veiculo ? $this->veiculo->getRenavam() : null ?>"
            >
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-3" for="marca">Marca:</label>
        <div class="col-sm-6">
            <input
                type="text"
                class="form-control"
                id="marca"
                name="marca"
                value="<?php echo $this->veiculo ? $this->veiculo->getMarca() : null ?>"
            >
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-3" for="modelo">Modelo:</label>
        <div class="col-sm-6">
            <input
                type="text"
                class="form-control"
                id="modelo"
                name="modelo"
                value="<?php echo $this->veiculo ? $this->veiculo->getModelo() : null ?>"
            >
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-3" for="ano">Ano:</label>
        <div class="col-sm-6">
            <input
                type="text"
                class="form-control"
                id="ano"
                name="ano"
                value="<?php echo $this->veiculo ? $this->veiculo->getAno() : null ?>"
            >
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-3" for="cor">Cor:</label>
        <div class="col-sm-6">
            <input
                type="text"
                class="form-control"
                id="cor"
                name="cor"
                value="<?php echo $this->veiculo ? $this->veiculo->getCor() : null ?>"
            >
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-success" id="btn-salvar">Salvar</button>
            <a href="/veiculo">
                <button type="button" class="btn btn-default">Voltar</button>
            </a>
        </div>
    </div>
</form>

<script>
$(document).ready(function(){
    const isEdit = $("#form-veiculo").attr('data-edit');
    jQuery.validator.setDefaults({
        success: "valid",
        highlight: function (input) {
            $(input).parents('.form-line').addClass('error');
            $('#btn-salvar').attr('disabled', true)
        },
        unhighlight: function (input) {
            $(input).parents('.form-line').removeClass('error');
            $('#btn-salvar').attr('disabled', false)
        },
        errorPlacement: function (error, element) {
            $(element).parents('.form-group').append(error);
            $('#btn-salvar').attr('disabled', true)
        }
    });

    $('#form-veiculo').validate({
        rules: {
            'placa': {
                required: true,
                maxlength: 7
            },
            'renavam': {
                required: true,
                maxlength: 30
            },
            'modelo': {
                required: true,
                maxlength: 20
            },
            'marca': {
                required: true,
                maxlength: 20
            },
            'cor': {
                required: true,
                maxlength: 20
            },
            'ano': {
                required: true,
                maxlength: 4,
                number: true
            }
        }
    });

    $("#form-veiculo").submit(function(e) {
        e.preventDefault();
        var form = $(this);
        if (form.valid()) {
            var actionUrl = form.attr('action');
            $("#btn-salvar").attr('disabled', true);
            $.ajax({
                type: "POST",
                url: actionUrl,
                dataType: 'json',
                data: form.serialize(),
                success: function() {
                    $("#btn-salvar").attr('disabled', false);
                    if (isEdit) {
                        swalEdit()
                    } else {
                        swalCadastro();
                    }
                },
                error: function () {
                    $("#btn-salvar").attr('disabled', false);
                    Swal.fire({
                        title: 'Ocorreu um erro, tente novamente em instantes!',
                        icon: 'error'
                    }).then((result) => {
                        window.location = '/motorista';
                    })
                }
            });
        }
    });

    function swalCadastro() {
        Swal.fire({
            title: 'Registro salvo!',
            showDenyButton: true,
            confirmButtonText: 'Sim',
            denyButtonText: 'Não',
            text: 'Deseja cadastrar um novo veículo?',
            icon: 'success'
        }).then((result) => {
            if (result.isConfirmed) {
                $("#form-veiculo").each (function(){
                   this.reset();
                });
            } else if (result.isDenied) {
                window.location = '/veiculo';
            }
        })
    }

    function swalEdit() {
        Swal.fire({
            title: 'Registro salvo!',
            icon: 'success'
        }).then((result) => {
            window.location = '/veiculo';
        })
    }
});
</script>