<?php
    $this->headScript()->prependFile($this->basePath() . '/js/home.js')
?>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-sm-10 col-md-10">
                <p class="text-center">Motoristas</p>
            </div>
            <div class="col-sm-2 col-md-2">
                <a href="/motorista/form">
                    <button class="btn btn-primary pull-right">Cadastrar</button>
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <th>Nome</th>
                <th>RG</th>
                <th class="text-right">Ações</th>
            </thead>
            <tbody>
            <?php
            if (!empty($motoristas)) {
                foreach ($motoristas as $motorista) {
            ?>
                <tr>
                    <td><?php echo $motorista->getNome(); ?></td>
                    <td><?php echo $motorista->getRg(); ?></td>
                    <td class="text-right">
                        <a href="/motorista/form/<?php echo $motorista->getId(); ?>">
                            <button class="btn btn-primary">
                                Editar
                            </button>
                        </a>
                        <button type="button" class="btn btn-danger btn-delete" data-url="/motorista/delete/<?php echo $motorista->getId(); ?>">
                            Excluir
                        </button>
                    </td>
                </tr>
            <?php }
            } else {
            ?>
            <tr class="text-center">
                <td colspan="3">Sem Registros</td>
            </tr>
            <?php
            }
                ?>
            </tbody>
        </table>
    </div>
</div>